// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnZanESehAIoJh-68OeOxV9YeXbg5pAss',
    appId: '1:961776985198:web:d24c66bf93e63cc012f27f',
    messagingSenderId: '961776985198',
    projectId: 'nutritrack10',
    authDomain: 'nutritrack10.firebaseapp.com',
    storageBucket: 'nutritrack10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg7KDlfaLOYQhYHpaDBra6xG5t39XY30o',
    appId: '1:961776985198:android:91d41cb3dd223ac712f27f',
    messagingSenderId: '961776985198',
    projectId: 'nutritrack10',
    storageBucket: 'nutritrack10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB91CGofYicwxKjtYKtejtcj8eoPkL9Lzw',
    appId: '1:961776985198:ios:28aa1328a88edaf412f27f',
    messagingSenderId: '961776985198',
    projectId: 'nutritrack10',
    storageBucket: 'nutritrack10.firebasestorage.app',
    iosBundleId: 'com.example.nutriTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB91CGofYicwxKjtYKtejtcj8eoPkL9Lzw',
    appId: '1:961776985198:ios:28aa1328a88edaf412f27f',
    messagingSenderId: '961776985198',
    projectId: 'nutritrack10',
    storageBucket: 'nutritrack10.firebasestorage.app',
    iosBundleId: 'com.example.nutriTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnZanESehAIoJh-68OeOxV9YeXbg5pAss',
    appId: '1:961776985198:web:a9cb678cc6a4119012f27f',
    messagingSenderId: '961776985198',
    projectId: 'nutritrack10',
    authDomain: 'nutritrack10.firebaseapp.com',
    storageBucket: 'nutritrack10.firebasestorage.app',
  );
}
